[2024-12-11T10:19:57.996+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:19:58.072+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:19:58.138+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:19:58.140+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-11T10:19:58.282+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-11 10:19:47.167832+00:00
[2024-12-11T10:19:58.315+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1180) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:19:58.321+0000] {standard_task_runner.py:72} INFO - Started process 1185 to run task
[2024-12-11T10:19:58.317+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-11T10:19:47.167832+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmp55yt6oqx']
[2024-12-11T10:19:58.337+0000] {standard_task_runner.py:105} INFO - Job 124: Subtask check_api_online
[2024-12-11T10:19:58.562+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:19:59.804+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:19:47.167832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:19:47.167832+00:00'
[2024-12-11T10:19:59.807+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:19:59.811+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:19:59.812+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-11 10:19:58.087207+00:00
[2024-12-11T10:19:59.819+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:19:59.820+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:19:59.821+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-11T10:19:59.847+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-11T10:19:59.877+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-12-11T10:20:00.348+0000] {http.py:204} ERROR - HTTP error: Not Found
[2024-12-11T10:20:00.351+0000] {http.py:205} ERROR - <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-12-11T10:20:00.446+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2024-12-11T10:20:00.453+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:20:00.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T10:20:00.680+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-11T10:20:14.545+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:20:14.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:14.620+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:14.621+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-11T10:20:14.680+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-11 10:19:47.167832+00:00
[2024-12-11T10:20:14.699+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:20:14.702+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-11T10:19:47.167832+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpz9drjijh']
[2024-12-11T10:20:14.708+0000] {standard_task_runner.py:72} INFO - Started process 1200 to run task
[2024-12-11T10:20:14.709+0000] {standard_task_runner.py:105} INFO - Job 127: Subtask check_api_online
[2024-12-11T10:20:14.896+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:20:15.736+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:19:47.167832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:19:47.167832+00:00'
[2024-12-11T10:20:15.741+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:20:15.742+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:20:15.743+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-11 10:20:14.596136+00:00
[2024-12-11T10:20:15.744+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:20:15.745+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:20:15.748+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-11T10:20:15.779+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-11T10:20:15.811+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-12-11T10:20:16.318+0000] {http.py:204} ERROR - HTTP error: Not Found
[2024-12-11T10:20:16.325+0000] {http.py:205} ERROR - <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-12-11T10:20:16.412+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2024-12-11T10:20:16.415+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:20:16.546+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T10:20:16.681+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T10:20:16.714+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-11T10:20:26.920+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:20:26.972+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:27.009+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:27.012+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-11T10:20:27.062+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-11 10:19:47.167832+00:00
[2024-12-11T10:20:27.078+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:20:27.078+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-11T10:19:47.167832+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpx1hvhhkp']
[2024-12-11T10:20:27.080+0000] {standard_task_runner.py:72} INFO - Started process 1204 to run task
[2024-12-11T10:20:27.080+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask check_api_online
[2024-12-11T10:20:27.191+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:20:27.665+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:19:47.167832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:19:47.167832+00:00'
[2024-12-11T10:20:27.666+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:20:27.667+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:20:27.668+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-11 10:20:26.974259+00:00
[2024-12-11T10:20:27.669+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:20:27.669+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:20:27.670+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-11T10:20:27.683+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-11T10:20:27.698+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-12-11T10:20:28.136+0000] {http.py:204} ERROR - HTTP error: Not Found
[2024-12-11T10:20:28.137+0000] {http.py:205} ERROR - <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-12-11T10:20:28.187+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2024-12-11T10:20:28.188+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:20:28.261+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T10:20:28.318+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T10:20:28.322+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-11T10:20:38.474+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:20:38.548+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:38.576+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:38.577+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-11T10:20:38.615+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-11 10:19:47.167832+00:00
[2024-12-11T10:20:38.628+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1206) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:20:38.631+0000] {standard_task_runner.py:72} INFO - Started process 1208 to run task
[2024-12-11T10:20:38.636+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-11T10:19:47.167832+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpi4hfrc9o']
[2024-12-11T10:20:38.638+0000] {standard_task_runner.py:105} INFO - Job 129: Subtask check_api_online
[2024-12-11T10:20:38.743+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:20:39.403+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:19:47.167832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:19:47.167832+00:00'
[2024-12-11T10:20:39.408+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:20:39.409+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:20:39.410+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-11 10:20:38.550647+00:00
[2024-12-11T10:20:39.412+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:20:39.413+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:20:39.414+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-11T10:20:39.439+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-11T10:20:39.458+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-12-11T10:20:40.142+0000] {http.py:204} ERROR - HTTP error: Not Found
[2024-12-11T10:20:40.143+0000] {http.py:205} ERROR - <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-12-11T10:20:40.190+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2024-12-11T10:20:40.192+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:20:40.263+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T10:20:40.351+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T10:20:40.372+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-11T10:20:51.735+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:20:51.792+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:51.830+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:20:51.831+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-11T10:20:51.880+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-11 10:19:47.167832+00:00
[2024-12-11T10:20:51.894+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1210) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:20:51.897+0000] {standard_task_runner.py:72} INFO - Started process 1220 to run task
[2024-12-11T10:20:51.898+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-11T10:19:47.167832+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpsvjf1hhj']
[2024-12-11T10:20:51.903+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask check_api_online
[2024-12-11T10:20:52.141+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:20:53.529+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:19:47.167832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:19:47.167832+00:00'
[2024-12-11T10:20:53.542+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:20:53.543+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:20:53.554+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-11 10:20:51.793449+00:00
[2024-12-11T10:20:53.570+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:20:53.586+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:20:53.602+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-11T10:20:53.650+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-11T10:20:53.675+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-12-11T10:20:54.193+0000] {http.py:204} ERROR - HTTP error: Not Found
[2024-12-11T10:20:54.207+0000] {http.py:205} ERROR - <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-12-11T10:20:54.296+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2024-12-11T10:20:54.300+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:20:54.380+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T10:20:54.480+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T10:20:54.493+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-11T10:21:10.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:21:10.143+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:21:10.192+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [queued]>
[2024-12-11T10:21:10.194+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-11T10:21:10.286+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-11 10:19:47.167832+00:00
[2024-12-11T10:21:10.312+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-11T10:19:47.167832+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpwt5x5yg2']
[2024-12-11T10:21:10.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:21:10.329+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask check_api_online
[2024-12-11T10:21:10.349+0000] {standard_task_runner.py:72} INFO - Started process 1224 to run task
[2024-12-11T10:21:10.574+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-11T10:19:47.167832+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:21:11.787+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:19:47.167832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:19:47.167832+00:00'
[2024-12-11T10:21:11.800+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:21:11.827+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:21:11.829+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-11 10:21:10.149401+00:00
[2024-12-11T10:21:11.831+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:21:11.832+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:21:11.843+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-11T10:21:11.875+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-11T10:21:11.899+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-12-11T10:21:13.406+0000] {http.py:204} ERROR - HTTP error: Not Found
[2024-12-11T10:21:13.419+0000] {http.py:205} ERROR - <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-12-11T10:21:13.436+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 160, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 74.650694 seconds exceeds the specified timeout of 60.0.
[2024-12-11T10:21:13.469+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-11T10:21:13.492+0000] {logging_mixin.py:190} INFO - Task start:2024-12-11 10:21:10.149401+00:00 end:2024-12-11 10:21:13.468420+00:00 duration:3.319019
[2024-12-11T10:21:13.493+0000] {logging_mixin.py:190} INFO - Task:<Task(HttpSensor): check_api_online> dag:<DAG: weather_data_pipeline> dagrun:<DagRun weather_data_pipeline @ 2024-12-11 10:19:47.167832+00:00: manual__2024-12-11T10:19:47.167832+00:00, state:running, queued_at: 2024-12-11 10:19:47.211735+00:00. externally triggered: True>
[2024-12-11T10:21:13.494+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 74.650694 seconds exceeds the specified timeout of 60.0.
[2024-12-11T10:21:13.495+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=weather_data_pipeline, task_id=check_api_online, run_id=manual__2024-12-11T10:19:47.167832+00:00, execution_date=20241211T101947, start_date=20241211T102110, end_date=20241211T102113
[2024-12-11T10:21:13.540+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:21:13.541+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 131 for task check_api_online (Sensor has timed out; run duration of 74.650694 seconds exceeds the specified timeout of 60.0.; 1224)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 160, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 74.650694 seconds exceeds the specified timeout of 60.0.
[2024-12-11T10:21:13.685+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-11T10:21:13.854+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T10:21:13.880+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
