[2024-12-11T10:56:02.911+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T10:56:02.949+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.load_weather_data manual__2024-12-11T10:30:40.208041+00:00 [queued]>
[2024-12-11T10:56:02.976+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.load_weather_data manual__2024-12-11T10:30:40.208041+00:00 [queued]>
[2024-12-11T10:56:02.979+0000] {taskinstance.py:2866} INFO - Starting attempt 12 of 12
[2024-12-11T10:56:03.020+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_weather_data> on 2024-12-11 10:30:40.208041+00:00
[2024-12-11T10:56:03.031+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1673) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-11T10:56:03.034+0000] {standard_task_runner.py:72} INFO - Started process 1675 to run task
[2024-12-11T10:56:03.035+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'load_weather_data', 'manual__2024-12-11T10:30:40.208041+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpw7of7qlv']
[2024-12-11T10:56:03.037+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask load_weather_data
[2024-12-11T10:56:03.132+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.load_weather_data manual__2024-12-11T10:30:40.208041+00:00 [running]> on host 4ccd8b9315ad
[2024-12-11T10:56:03.772+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T10:30:40.208041+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T10:30:40.208041+00:00'
[2024-12-11T10:56:03.775+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T10:56:03.776+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T10:56:03.777+0000] {logging_mixin.py:190} INFO - Current task name:load_weather_data state:running start_date:2024-12-11 10:56:02.950806+00:00
[2024-12-11T10:56:03.778+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-11T10:56:03.779+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T10:56:03.780+0000] {sql.py:278} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS daily_weather (
            city VARCHAR(255),
            temperature DECIMAL(10, 2),
            pressure DECIMAL(10, 2),
            humidity DECIMAL(10, 2),
            timestamp TIMESTAMP
        );

        INSERT INTO daily_weather (city, temperature, pressure, humidity, timestamp)
        VALUES (%(city)s, %(temperature)s, %(pressure)s, %(humidity)s, %(timestamp)s);
    
[2024-12-11T10:56:03.797+0000] {base.py:84} INFO - Retrieving connection 'portland_data'
[2024-12-11T10:56:03.811+0000] {base.py:84} INFO - Retrieving connection 'portland_data'
[2024-12-11T10:56:03.918+0000] {sql.py:544} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS daily_weather (
            city VARCHAR(255),
            temperature DECIMAL(10, 2),
            pressure DECIMAL(10, 2),
            humidity DECIMAL(10, 2),
            timestamp TIMESTAMP
        );

        INSERT INTO daily_weather (city, temperature, pressure, humidity, timestamp)
        VALUES (%(city)s, %(temperature)s, %(pressure)s, %(humidity)s, %(timestamp)s);
    , parameters: {'city': 'None', 'temperature': 'None', 'pressure': 'None', 'humidity': 'None', 'timestamp': 'None'}
[2024-12-11T10:56:03.934+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 547, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "None"
LINE 11:         VALUES ('None', 'None', 'None', 'None', 'None');
                                 ^

[2024-12-11T10:56:03.954+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-11T10:56:03.955+0000] {logging_mixin.py:190} INFO - Task start:2024-12-11 10:56:02.950806+00:00 end:2024-12-11 10:56:03.953438+00:00 duration:1.002632
[2024-12-11T10:56:03.956+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): load_weather_data> dag:<DAG: weather_data_pipeline> dagrun:<DagRun weather_data_pipeline @ 2024-12-11 10:30:40.208041+00:00: manual__2024-12-11T10:30:40.208041+00:00, state:running, queued_at: 2024-12-11 10:53:51.915556+00:00. externally triggered: True>
[2024-12-11T10:56:03.957+0000] {logging_mixin.py:190} INFO - Failure caused by invalid input syntax for type numeric: "None"
LINE 11:         VALUES ('None', 'None', 'None', 'None', 'None');
                                 ^
[2024-12-11T10:56:03.957+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=load_weather_data, run_id=manual__2024-12-11T10:30:40.208041+00:00, execution_date=20241211T103040, start_date=20241211T105602, end_date=20241211T105603
[2024-12-11T10:56:03.981+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T10:56:03.984+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 149 for task load_weather_data (invalid input syntax for type numeric: "None"
LINE 11:         VALUES ('None', 'None', 'None', 'None', 'None');
                                 ^
; 1675)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 547, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "None"
LINE 11:         VALUES ('None', 'None', 'None', 'None', 'None');
                                 ^

[2024-12-11T10:56:04.060+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-11T10:56:04.091+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T10:56:04.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
