[2024-12-09T18:33:02.366+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T18:33:02.389+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-09T18:30:27.630955+00:00 [queued]>
[2024-12-09T18:33:02.402+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-09T18:30:27.630955+00:00 [queued]>
[2024-12-09T18:33:02.403+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2024-12-09T18:33:02.422+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): check_api_online> on 2024-12-09 18:30:27.630955+00:00
[2024-12-09T18:33:02.430+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T18:33:02.432+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2024-12-09T18:33:02.432+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'check_api_online', 'manual__2024-12-09T18:30:27.630955+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpm8z32h_s']
[2024-12-09T18:33:02.434+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask check_api_online
[2024-12-09T18:33:02.493+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.check_api_online manual__2024-12-09T18:30:27.630955+00:00 [running]> on host 4ccd8b9315ad
[2024-12-09T18:33:02.829+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='check_api_online' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T18:30:27.630955+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T18:30:27.630955+00:00'
[2024-12-09T18:33:02.830+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-09T18:33:02.831+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-09T18:33:02.831+0000] {logging_mixin.py:190} INFO - Current task name:check_api_online state:running start_date:2024-12-09 18:33:02.390844+00:00
[2024-12-09T18:33:02.832+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-09T18:33:02.832+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T18:33:02.833+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-09T18:33:02.834+0000] {http.py:137} INFO - Poking: https://api.openweathermap.org/data/2.5/weather?q=Portland&appid=dd24fafbe11ff5c183032972a933481d
[2024-12-09T18:33:02.863+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 160, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 154, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 170, in run
    session = self.get_conn(headers)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 110, in get_conn
    conn = self.get_connection(self.http_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `openweather_api` isn't defined
[2024-12-09T18:33:02.876+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-09T18:33:02.878+0000] {logging_mixin.py:190} INFO - Task start:2024-12-09 18:33:02.390844+00:00 end:2024-12-09 18:33:02.876264+00:00 duration:0.48542
[2024-12-09T18:33:02.879+0000] {logging_mixin.py:190} INFO - Task:<Task(HttpSensor): check_api_online> dag:<DAG: weather_data_pipeline> dagrun:<DagRun weather_data_pipeline @ 2024-12-09 18:30:27.630955+00:00: manual__2024-12-09T18:30:27.630955+00:00, state:running, queued_at: 2024-12-09 18:30:27.645822+00:00. externally triggered: True>
[2024-12-09T18:33:02.880+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `openweather_api` isn't defined
[2024-12-09T18:33:02.881+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=check_api_online, run_id=manual__2024-12-09T18:30:27.630955+00:00, execution_date=20241209T183027, start_date=20241209T183302, end_date=20241209T183302
[2024-12-09T18:33:02.913+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T18:33:02.914+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task check_api_online (The conn_id `openweather_api` isn't defined; 196)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 160, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 154, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 170, in run
    session = self.get_conn(headers)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 110, in get_conn
    conn = self.get_connection(self.http_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `openweather_api` isn't defined
[2024-12-09T18:33:02.970+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-09T18:33:02.998+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T18:33:03.002+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
